#!name = 京东去广告
#!desc = 移除京东开屏广告，精简我的页面产品推广，下滑或点击商品详情即可显示比价信息。\n首次使用需要下载慢慢买APP，点击我的页面获取CK数据，无需登录。
#!author = RuCu6[https://github.com/RuCu6], githubdulong[https://github.com/githubdulong],wish[https://github.com/mist-whisper]
#!icon = https://raw.githubusercontent.com/mist-whisper/Icon/master/App_icon/120px/JD.png
#!tag = 去广告增强
#!homepage = https://github.com/mist-whisper/Shadowrocket/blob/master/README.md
#!date = 2025-04-21 23:35:00

[Rule]
DOMAIN,dns.jd.com,REJECT
URL-REGEX,"^http:\/\/\w{32}\.jddebug\.com\/diagnose\?",REJECT
IP-CIDR,101.124.19.122/32,REJECT,no-resolve
IP-CIDR6,2402:db40:5100:1011::5/128,REJECT,no-resolve

[URL Rewrite]
^https:\/\/api\.m\.jd\.com\/client\.action\?functionId=(searchBoxWord|stationPullService|uniformRecommend[06]) - reject-dict
^https?:\/\/m\.360buyimg\.com\/mobilecms\/s1125x2436_jfs - reject-200

[Script]
移除京东广告 = type=http-response, pattern=^https:\/\/api\.m\.jd\.com\/client\.action\?functionId=(deliverLayer|getTabHomeInfo|myOrderInfo|orderTrackBusiness|personinfoBusiness|start|welcomeHome), script-path=https://raw.githubusercontent.com/mist-whisper/Script/refs/heads/master/JD/JD_remove_ads.js, requires-body=true

获取慢慢买ck = type=http-request, pattern=^https?:\/\/apapia-sqk-weblogic\.manmanbuy\.com/baoliao\/center\/menu, script-path=https://raw.githubusercontent.com/mist-whisper/Script/master/JD/JD_Price.js, requires-body=true

京东比价 = type=http-response, pattern=^https:\/\/in\.m\.jd\.com\/product\/graphext\/\d+\.html, script-path=https://raw.githubusercontent.com/mist-whisper/Script/master/JD/JD_Price.js, requires-body=true, timeout=30

[MITM]
hostname = %APPEND% in.m.jd.com, apapia-sqk-weblogic.manmanbuy.com, m.360buyimg.com
