#!name = Spotify去广告
#!desc = 过滤Spotify播放广告，移除随机播放，恢复歌手和专辑列表的正常展示。建议重新登录并清除缓存，且音质不能设置为超高，仅建议iOS 15及以上设备使用。
#!openUrl = 
#!author = app2smile[https://github.com/app2smile]
#!tag = 解锁去广告
#!homepage = https://github.com/mist-whisper/Loon/blob/master/README.md
#!icon = https://raw.githubusercontent.com/mist-whisper/Icon/master/App_icon/120px/Spotify.png
#!date = 2025-05-03 21:49:00

[Script]
JSON处理 = type=http-request,type=http-request,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js
Proto处理 = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,script-update-interval=0

[MitM]
hostname=spclient.wg.spotify.com
