#!name = YouTube去广告
#!desc = 移除YouTube视频、瀑布流、搜索和Shorts中的广告，移除底部的上传按钮和Shorts按钮，增加画中画及字幕翻译功能。移除YouTube Music底部的上传、选段和升级按钮，增加歌词翻译，支持二者的后台播放。支持Premium订阅用户使用，不支持tvOS设备。
#!author = Maasea[https://github.com/Maasea]
#!icon = https://raw.githubusercontent.com/mist-whisper/Icon/master/App_icon/120px/YouTube.png
#!category = 去广告
#!homepage=https://github.com/mist-whisper/Shadowrocket/blob/master/README.md
#!date = 2025-04-10

#!arguments = 隐藏上传按钮:true, 隐藏选段按钮:true, 隐藏短视频按钮:true, 启用调试模式:false, 字幕翻译语言:zh-Hans, 歌词翻译语言:zh-Hans
#!arguments-desc=- 屏蔽参数：[true, false] \n- 翻译参数：[语言代码, off] \n- 脚本引擎：[auto, jsc, webview]\n\n1. 语言代码遵循 Google Translate Languages Codes, 当填入 off 时关闭翻译\n2. 推荐使用 jsc 引擎，但你仍可以切换成 webview 体验\n3. 开启调试模式用于输出更多日志

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com),(PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com),(PROTOCOL,UDP)),REJECT

[URL Rewrite]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad - reject-200

[Script]
youtube.response = type=http-response, pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch), script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.response.js, requires-body=true, binary-body-mode=true, max-size=-1, argument="{"lyricLang":"off","captionLang":"off","blockUpload":true,"blockImmersive":true,"blockShorts":false,"debug":false}"

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com
